In [1]:
import torch
import numpy as np

In [2]:
x = torch.arange(6).reshape(3, 2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

## Slicing

In [3]:
x[1, 1]

tensor(3)

In [4]:
type(x[1, 1])

torch.Tensor

In [5]:
x[:, 1]

tensor([1, 3, 5])

In [6]:
x[:, 1:]

tensor([[1],
        [3],
        [5]])

## Reshaping

In [8]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

We just viewed, not modify it

In [10]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x.reshape(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

With reshape we also don't modify the tensor. It has a similar behavior to `view()`. There are some little differences and can be see on internet.

In [12]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x = x.reshape(2, 5)

In [14]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

`view()` reflects more recent data

In [17]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x.shape

torch.Size([10])

In [19]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
z = x.view(2, 5)
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Now `z` is linked with `x`. This is bc we use `view()`

In [24]:
x[0] = 9999
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [25]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [26]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x.shape

torch.Size([10])

In [28]:
# Infer what the 2nd dimension
x.view(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
# Infer 1st dimension
x.view(-1, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [32]:
a = torch.tensor([1., 2., 3.])
a

tensor([1., 2., 3.])

In [33]:
b = torch.tensor([4., 5., 6.])
b

tensor([4., 5., 6.])

In [35]:
a.dtype

torch.float32

In [36]:
a + b

tensor([5., 7., 9.])

In [37]:
torch.add(a, b)

tensor([5., 7., 9.])

In [38]:
a.mul(b)
# a = a + b

tensor([ 4., 10., 18.])