# PyTorch Basics

## Tensor Basics

In [1]:
# %% Imports
import torch
import numpy as np

Testing torch

In [2]:
torch.__version__

'1.10.2'

In [3]:
arr = np.array([1, 2, 3, 4, 5])

arr.dtype

dtype('int32')

In [4]:
type(arr)

numpy.ndarray

In [7]:
# Converting to tensor
x = torch.from_numpy(arr)

In [8]:
type(x)

torch.Tensor

In [9]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [10]:
x.dtype

torch.int32

In [16]:
arr2d = np.arange(0.0, 12.0)
arr2d = arr2d.reshape(4, 3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [17]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

Torch mantiene una conexión entre el array original y el objeto Torch.

Anteriormente creamos una variable **arr** y con esa creamos un tensor **x**.

Sí modificamos **arr** veremos que **x** también se verá modificada.

In [18]:
arr[0] = 99
arr

array([99,  2,  3,  4,  5])

In [19]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

Lo anterior no aplica si utilizamos directamente `torch.tensor()`

In [21]:
my_arr = np.arange(0, 10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_tensor = torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [24]:
my_other_tensor = torch.from_numpy(my_arr)
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [25]:
my_arr[0] = 9999
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

torch.tensor()

In [26]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

torch.from_numpy()

In [27]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       dtype=torch.int32)