In [1]:
import torch
import numpy as np

In [2]:
a = torch.tensor([1., 2., 3.])
a

tensor([1., 2., 3.])

In [3]:
b = torch.tensor([4., 5., 6.])
b

tensor([4., 5., 6.])

In [4]:
a.mul(b)

tensor([ 4., 10., 18.])

In [5]:
a.dot(b)

tensor(32.)

In [7]:
a = torch.tensor([[0, 2, 4], [1, 3, 5]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [10]:
b = torch.tensor([[6, 7], [8, 9], [10, 11]])
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [13]:
a.shape

torch.Size([2, 3])

In [12]:
b.shape

torch.Size([3, 2])

Using shapes we have the multiplication

$$
    [2, 3] X [3, 2]

$$

Inner values must coincide [2, 3] <-> [3, 2]

The outer parts are the size of the result. -> [2, 3] [3, 2] <-  result: [2, 2]

In [15]:
# Matrix multiplication
torch.mm(a, b)

tensor([[56, 62],
        [80, 89]])

In [16]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [17]:
x = torch.tensor([2., 3., 4., 5.])
x

tensor([2., 3., 4., 5.])

In [18]:
x.norm()

tensor(7.3485)

In [19]:
x.numel()

4

In [20]:
len(x)

4

In [21]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [22]:
len(a)

2

In [23]:
a.numel()

6