# PyTorch Basics

## Tensor Basics

In [3]:
import torch
import numpy as np

In [4]:
new_arr = np.array([1, 2, 3])

## Difference between torch.Tensor and torch.tensor

In [5]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [7]:
my_tensor = torch.Tensor(new_arr)
my_tensor

tensor([1., 2., 3.])

The main difference is that torch.Tensor converts to a float directly!

In [8]:
my_tensor.dtype

torch.float32

## Initialization of tensors

In [10]:
# Allocate the memory
# Will be values close to 0
torch.empty(2, 2)

tensor([[6.1531e-39, 6.1531e-39],
        [6.3368e-39, 1.1571e-38]])

In [11]:
# Store true 0's
torch.zeros(4, 3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [12]:
# We can use ones too
torch.ones(4, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
# Or arange as numpy
torch.arange(0, 18, 2).reshape(3, 3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [16]:
torch.linspace(0, 18, 12).reshape(3, 4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [17]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

Changing data types

In [19]:
my_tensor = torch.tensor([1, 2, 3])
my_tensor.dtype

torch.int64

Changing datatype

In [21]:
my_tensor = my_tensor.type(torch.int32)
my_tensor.dtype

torch.int32

In [22]:
# Random samples over random dist
torch.rand(4, 3)

tensor([[0.2046, 0.9969, 0.0017],
        [0.2832, 0.4489, 0.2654],
        [0.8808, 0.1706, 0.4683],
        [0.5559, 0.7041, 0.3772]])

In [23]:
# Random data with standard norm dist
torch.randn(4, 3)

tensor([[ 0.4008,  0.3864, -2.1939],
        [-1.1893,  0.3006,  0.5569],
        [ 0.4244,  0.1796,  1.0663],
        [-0.7491, -1.3399,  1.1659]])

In [25]:
torch.randint(low=0, high=10, size=(5, 5))

tensor([[9, 8, 4, 4, 7],
        [4, 2, 7, 6, 8],
        [4, 7, 0, 2, 0],
        [9, 0, 9, 2, 2],
        [8, 4, 8, 6, 9]])

In [26]:
x = torch.zeros(2, 5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [27]:
x.shape

torch.Size([2, 5])

Random numbers with the shape of other tensor

In [28]:
torch.rand_like(x)

tensor([[0.3652, 0.5450, 0.8331, 0.1924, 0.9343],
        [0.2889, 0.8391, 0.5776, 0.3201, 0.5400]])

In [29]:
torch.randn_like(x)

tensor([[ 0.7049,  0.2899,  0.0793, -1.8422,  0.2254],
        [ 1.6535,  0.7145,  0.9945,  1.4323, -0.2453]])

In [30]:
torch.randint_like(x, low=0, high=11)

tensor([[ 5., 10.,  3.,  7.,  4.],
        [ 4.,  0.,  6.,  1.,  3.]])

Defining a seed

In [31]:
torch.manual_seed(42)

In [32]:
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])